name: SSE CI/CD
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Run clang-format
      run: |
        clang-format -i tests/*.cpp --dry-run --Werror
        clang-format -i src/*.cpp --dry-run --Werror
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies    
      run: |
        sudo apt-get update && sudo apt-get install -y \
        libboost-all-dev \
        build-essential \
        cmake \
        git \
        libeigen3-dev && \
        sudo git clone https://github.com/jbeder/yaml-cpp /src/yaml-cpp && \
        mkdir /src/yaml-cpp/build && \
        cd /src/yaml-cpp/build && \
        cmake .. && \
        make && \
        make install && \
        cd .. && \
        rm -rf build

    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Create build directory
      run: mkdir build
    - name: Configure build
      run: cd build && cmake ..
    - name: Build
      run: cd build && make
    - name: Save build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/