name: SSE CI/CD
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Run clang-format
      run: |
        clang-format -i tests/*.cpp --dry-run --Werror
        clang-format -i src/*.cpp --dry-run --Werror